use_frameworks!

target 'SwiftExtensions_Example' do
  pod 'SwiftExtensions', :path => '../'

  target 'SwiftExtensions_Tests' do
    inherit! :search_paths
    
    pod 'YYCategories', '~> 1.0.4'

  end
end
