use_frameworks!
inhibit_all_warnings!

platform :ios, '9.0'

target 'Koala_Example' do
  pod 'Koala', :path => '../'

  target 'Koala_Tests' do
    inherit! :search_paths
    
    pod 'YYCategories', '~> 1.0.4'

  end
end

